version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_AUTH_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    volumes:
      - ./workflow.json:/home/node/.n8n/workflows/workflow.json
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    
volumes:
  n8n_data:

# SECURITY NOTE: 
# - Set N8N_AUTH_PASSWORD in your .env file
# - Never commit .env files to version control
# - Use strong, unique passwords for production